AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Email Processing

Globals:
  Function:
    Timeout: 20

Resources:
  AWSEmailProcessing:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.dex.Main::handleRequest
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 180
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        SES:
          Type: SES
          Properties:
            Rules:
              - Name: MyRuleName
                Enabled: true
                Recipients:
                  - "example@example.com"

Outputs:
  AWSEmailProcessingApi:
    Description: "API Gateway endpoint URL for Prod stage for AWS Email Processing function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/email/"
  AWSEmailProcessing:
    Description: "AWS Email Processing Lambda Function ARN"
    Value: !GetAtt AWSEmailProcessing.Arn
  AWSEmailProcessingFnIamRole:
    Description: "Implicit IAM Role created for AWS Email Processing function"
    Value: !GetAtt AWSEmailProcessingRole.Arn

#AWSTemplateFormatVersion: '2010-09-09'
#Transform: AWS::Serverless-2016-10-31
#Description: >
#  AWS Email Processing
#
## More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
#Globals:
#  Function:
#    Timeout: 20
#
#Resources:
#  AWSEmailProcessingFn:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: AWSEmailProcessingFn
#      Handler: dex.com.Main::handleRequest
#      Runtime: java11
#      Architectures:
#        - x86_64
#      MemorySize: 180
#      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
#        Variables:
#          PARAM1: VALUE
#          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
#      ServiceToken:
#      Events:
##        HelloWorld:
##          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
##          Properties:
##            Path: /email
##            Method: post
#            SES:
#              Type: SES
#              Properties:
#                Rules:
#                  - Name: MyRuleName
#                    Enabled: true
#                    Recipients:
#                      - "example@example.com"
#
#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  AWSEmailProcessingFn:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt AWSEmailProcessingFn.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
